# Generated by Django 5.2.3 on 2025-06-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_of_calm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dientry',
            old_name='memo',
            new_name='content',
        ),
    ]
