# Generated by Django 5.2.3 on 2025-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_of_calm', '0003_rename_creted_at_dientry_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dientry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entry_images/'),
        ),
    ]
